### ISSUE TITLE
upgrade Virtual Try-on model

### ISSUE THREAD

**Issue by hankyuwon** [troymerai/COSMIC-tryon#38]
It seems possible to upgrade the Virtual Try-on model.
(ACGPN -> Flow-Style-VTON)

In the Virtual Try-on on VTON task, the current state-of-the-art is Flow-Style-VTON (ACGPN is in 8th place).

https://paperswithcode.com/sota/virtual-try-on-on-viton

**Comment by troymerai** [comment]
I appreciate your interest in upgrading the Virtual Try-on model. If you could create a pull request with your code, I will make a review. thanks!
